### ISSUE TITLE
Ability to hide "User Agent" tab from panel

### ISSUE THREAD

**Issue by tylertadej** [Sotaneum/storybook-addon-useragent#10]
Nice addon. It is very useful, however my project doesn't need a new tab on every story.

The tab didn't disappear using the addon ID "user-agent". Is there another method of hiding the tab? The code below works for the Actions tab.

```
export const parameters = {
  ...
  actions: { disabled: true }
};
```

Thanks!

**Comment by Sotaneum** [comment]
@tylertadej 
Thanks for the issue! The work has been completed and reflected in version [0.4.0](https://www.npmjs.com/package/storybook-addon-useragent).

**Comment by tylertadej** [comment]
Works great, thank you!
