### ISSUE TITLE
Add Support for React v18

### ISSUE THREAD

**Issue by pjbreaux** [Sotaneum/storybook-addon-useragent#4]
Hello, I have tested this with React 18.2.0 and it works well. Do you have any plans to officially support react 18?

Thanks very much!

**Comment by Sotaneum** [comment]
@pjbreaux Thanks for the issue 👍🏼 

I tested it on React 18.

As a result, a warning appears, but it was confirmed that there is no functional problem.

Added support list in version 0.3(#8).
